### ISSUE TITLE
game server

### ISSUE THREAD

**Issue by kehiy** [scorpio-demon/Chest.js#1]
hello, how are you going to implement the game server?
is that a core? or an app?

**Comment by scorpio-demon** [comment]
Hi
Please explain exactly what do you mean?

This is a socket based core for real time chat apps.

Do you want to create a game?

**Comment by kehiy** [comment]
@scorpio-demon you said this is a chess game server, I want to know do you use WebSocket or UDP.
from your message, I found you are going to use Websocket.
thanks.
